# nb 09: Identify EE-TCP



In [6]:
import numpy as np
import rospy
import spatialmath as sm
from tqdm.notebook import trange, tqdm

import hrr_cobot_robot
import hrr_common

np.set_printoptions(suppress=True, precision=4)

In [7]:
hrr_common.utils.set_ros_environment(ros_master = 'hrrcobotLinux54')

current hostname:	pizza
current IP:      	129.187.147.180
ROS-MASTER-URI:  	http://hrrcobotLinux54:11311


In [8]:
rospy.init_node("hrr_cobot_check_tcps")

In [9]:
cobot = hrr_cobot_robot.HrrCobotControl.from_ros('/hrr_cobot')

In [41]:
# cobot.init_sns_vel()

In [6]:
# drive to save location to start rotation motion

In [6]:
# v_test = np.zeros(6)
# for t in trange(1000):
# #     v_test[2] = -1e-3
#     v_test[0] =  5e-3
    
#     cobot.update(u_cmd=v_test, u_cmd_frame="hrr_cobot.base_link", sleep=True)
# cobot.stop()

In [7]:
free_space_pose = sm.SE3(np.r_[0.4612, 0.1168, 0.75])
free_space_pose.A[:3, :3] = sm.base.rpy2r(-np.pi/2.0, np.pi/4.0, np.pi, unit="rad")

In [45]:
cobot.goTo(free_space_pose)

In [42]:
contact_pose = sm.SE3(np.r_[0.08, 0., -0.1175]) @ cobot.T_B_E_robot
cobot.goTo(contact_pose)

In [38]:
# move_back = sm.SE3(np.r_[-0.08, 0., 0.1175]) @ cobot.T_B_E_robot
# cobot.goTo(move_back)

In [26]:
cobot.change_tool("shaftgrinder")

True

In [27]:
cobot.T_E_C_robot

  -0.7071    0         0.7071    0.06682   
   0.7071    0         0.7071    0.06682   
   0         1         0         0.1555    
   0         0         0         1         


In [30]:
q_test = list(cobot.IK(hrr_common.utils.spatial.calc_EE_goal_pose(B_normal=np.r_[0., 0., 1],
                                                                  B_p_location=cobot.T_B_C_robot.t,
                                                                  B_y_axis = np.r_[0., 1., 0.],
                                                                  T_C_E=cobot.T_E_C_robot.inv()), check=True))

In [33]:
idx = np.argsort(np.linalg.norm((q_test - cobot.q)[:,:3], axis=1))
q_des = np.array(q_test)[idx][0]
q_des, cobot.q

(array([ 0.5359,  0.2703, -1.3578, -1.5368,  2.1057,  2.4228]),
 array([-0.0234, -0.2743, -1.7423,  0.2293,  1.5898,  0.3809]))

In [35]:
cobot.move_to_joint_pose(q_des)

In [ ]:
cobot.

In [50]:
cobot.change_tool("screwdriver")
cobot.T_E_C_robot

   3.462e-12 -0.7071    0.7071    0.1584    
   3.462e-12  0.7071    0.7071    0.1584    
  -1         0         4.897e-12  0.1475    
   0         0         0         1         


In [51]:
q_test = list(cobot.IK(hrr_common.utils.spatial.calc_EE_goal_pose(B_normal=np.r_[0., 0., 1],
                                                                  B_p_location=cobot.T_B_C_robot.t,
                                                                  B_y_axis = np.r_[0., -1., 0.],
                                                                  T_C_E=cobot.T_E_C_robot.inv()), check=True))

In [52]:
idx = np.argsort(np.linalg.norm((q_test - cobot.q)[:,:3], axis=1))
q_des = np.array(q_test)[idx][0]
q_des, cobot.q

(array([ 0.0435,  0.8441, -0.4916,  2.957 ,  2.9026,  0.6059]),
 array([-0.4039,  0.1721, -1.476 ,  1.5368,  1.9723, -0.8707]))

In [11]:
cobot.T_B_C_robot

  -0.04604   0.8864    0.4606    0.443     
   0.8922    0.2439   -0.3802   -0.3658    
  -0.4494    0.3934   -0.8021    0.3246    
   0         0         0         1         


In [40]:
cobot.FK(q) @ sm.SE3.Rz(45, "deg") @ cobot.T_E_C_robot

  -0.001629  1        -4.639e-05  0.5774    
   1         0.001629 -0.0079    0.1189    
  -0.0079   -5.925e-05 -1         0.1112    
   0         0         0         1         


In [39]:
sm.SE3.Rz(-45, "deg") @ cobot.T_E_C_robot

   4.896e-12  0         1         0.0945    
   1         0        -4.896e-12 -8.667e-13  
   0         1         0         0.1555    
   0         0         0         1         


In [ ]:
q_test = list(cobot.IK(hrr_common.utils.spatial.calc_EE_goal_pose(B_normal=np.r_[0., 0., 1],
                                                                  B_p_location=cobot.T_B_C_robot.t,
                                                                  B_y_axis = np.r_[0., 1., 0.],
                                                                  T_C_E=cobot.T_E_C_robot.inv()), check=True))

In [ ]:
hrr_common.utils.spatial.calc_EE_goal_pose(B_normal=np.r_[0., 0., 1],
                                           B_p_location=cobot.T_B_C_robot.t,
                                           B_y_axis = np.r_[0., 1., 0.],
                                           T_C_E=cobot.T_E_C_robot.inv()), check=True))